name: build-and-test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Installer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Démarrer tout avec docker-compose
      - name: Start services
        run: docker compose up -d --build

      # 4️⃣ Attendre MySQL + backend + frontend
      - name: Wait for services
        run: sleep 30

      # 5️⃣ Tester le backend dans le réseau docker
      - name: Test Backend API
        run: |
          docker run --rm --network=global-polling-platform_app-network curlimages/curl:8.5.0 \
            curl -f http://backend:3001/polls

      # 6️⃣ Tester le frontend dans le réseau docker
      - name: Test Frontend
        run: |
          docker run --rm --network=global-polling-platform_app-network curlimages/curl:8.5.0 \
            curl -f http://frontend:3000

      # 7️⃣ Arrêter et nettoyer
      - name: Stop containers
        if: always()
        run: docker compose down -v
