name: build-and-test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Installer Docker (actions runner l'a déjà)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Build Backend (NestJS)
      - name: Build Backend
        run: docker build -t backend ./backend/api

      # 4️⃣ Build Frontend (Next.js)
      - name: Build Frontend
        run: docker build -t frontend ./frontend

      # 5️⃣ Lancer docker-compose pour tests
      - name: Start services
        run: docker compose up -d

      # 6️⃣ Vérifier que le backend répond
      - name: Test Backend API
        run: |
          sleep 15  # attendre MySQL + backend démarrage
          curl -f http://localhost:3001/polls || exit 1

      # 7️⃣ Vérifier que le frontend démarre
      - name: Test Frontend
        run: |
          curl -f http://localhost:3000 || exit 1

      # 8️⃣ Arrêter et nettoyer
      - name: Stop containers
        run: docker compose down -v
