name: build-and-test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Installer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Build Backend (NestJS)
      - name: Build Backend
        run: docker build -t backend ./backend/api

      # 4️⃣ Build Frontend (Next.js)
      - name: Build Frontend
        run: docker build -t frontend ./frontend

      # 5️⃣ Lancer docker-compose pour tests
      - name: Start services
        run: docker compose up -d

      # 6️⃣ Vérifier que le backend répond
      - name: Test Backend API
        run: |
          sleep 15  # attendre MySQL + backend démarrage
          docker run --rm --network=global-polling-platform_app-network curlimages/curl:8.5.0 \
            -f http://backend:3001/api/polls || exit 1

      # 7️⃣ Vérifier que le frontend démarre
      - name: Test Frontend
        run: |
          docker run --rm --network=global-polling-platform_app-network curlimages/curl:8.5.0 \
            -f http://frontend:3000 || exit 1

      # 8️⃣ Arrêter et nettoyer
      - name: Stop containers
        run: docker compose down -v
